name: Repository Dispatch
on:
  repository_dispatch:
    types: [upstream-build]
jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}